return function (s)
 local r
 if s.run then
 print("Module TDA7313 is run")
   gpio.mode(s.pin_p, gpio.OUTPUT)
   gpio.mode(s.pin_m, gpio.OUTPUT)
   gpio.write(s.pin_p, s.power)
   gpio.write(s.pin_m, s.mute) 
   print(i2c.setup(0, s.sda, s.scl, i2c.SLOW))
  local mytimer = tmr.create()
  mytimer:register(1000, tmr.ALARM_SINGLE, function (t) 
   dofile("TDA7313.lua")(s)
  end)
  mytimer:start()
  r=true
 end
 return r
end